
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ADD MULT NUM SUB\nS : Exp\n\nExp : Exp ADD Termo\n\nExp : Exp SUB Termo\n\nExp : Termo\n\nTermo : Termo MULT Factor\n\nTermo : Factor\n\nFactor : NUM\n\nFactor : '(' Exp ')'\n"
    
_lr_action_items = {'NUM':([0,6,7,8,9,],[5,5,5,5,5,]),'(':([0,6,7,8,9,],[6,6,6,6,6,]),'$end':([1,2,3,4,5,11,12,13,14,],[0,-1,-4,-6,-7,-2,-3,-5,-8,]),'ADD':([2,3,4,5,10,11,12,13,14,],[7,-4,-6,-7,7,-2,-3,-5,-8,]),'SUB':([2,3,4,5,10,11,12,13,14,],[8,-4,-6,-7,8,-2,-3,-5,-8,]),')':([3,4,5,10,11,12,13,14,],[-4,-6,-7,14,-2,-3,-5,-8,]),'MULT':([3,4,5,11,12,13,14,],[9,-6,-7,9,9,-5,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'Exp':([0,6,],[2,10,]),'Termo':([0,6,7,8,],[3,3,11,12,]),'Factor':([0,6,7,8,9,],[4,4,4,4,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> Exp','S',1,'p_global','sin.py',6),
  ('Exp -> Exp ADD Termo','Exp',3,'p_exp_add','sin.py',12),
  ('Exp -> Exp SUB Termo','Exp',3,'p_exp_sub','sin.py',18),
  ('Exp -> Termo','Exp',1,'p_exp_term','sin.py',24),
  ('Termo -> Termo MULT Factor','Termo',3,'p_term_mult','sin.py',30),
  ('Termo -> Factor','Termo',1,'p_term_factor','sin.py',36),
  ('Factor -> NUM','Factor',1,'p_factor_num','sin.py',42),
  ('Factor -> ( Exp )','Factor',3,'p_factor_group','sin.py',48),
]
